### ISSUE TITLE
Getting import request error

### ISSUE THREAD

**Issue by cryptonic01** [colental/byob#1]
Getting  import cv2 Error while starting the server

Traceback (most recent call last):
  File "C:\Users\x\Desktop\byob-master\byob-master\byob\server.py", line 44, in <module>
    import cv2
  File "C:\Python27\lib\site-packages\cv2\__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

thanks

**Comment by colental** [comment]
I looked into this issue and found that the “requirements-windows.txt” file was incomplete. I updated it so this issue should be fixed.  Remember after you download BYOB to first run `pip install -r requirements-windows.txt` (Windows platforms) or `pip install -r requirements.txt` (non-Windows platforms) before you proceed.
