### ISSUE TITLE
pastebin flag throwing type error

### ISSUE THREAD

**Issue by chrissparksnj** [colental/byob#11]
Im trying the following command:
`python client.py {ip.ip.ip.ip} {port} --pastebin {api_key}`

And im getting the following error:
`TypeError: pastebin() got an unexpected keyword argument 'api_dev_key'`

**Comment by colental** [comment]
Thanks for bringing this to my attention! I'm attempting to replicate the issue and will fix it ASAP!

**Comment by colental** [comment]
Ok this issue should now be fixed.
