### ISSUE TITLE
Cannot run server

### ISSUE THREAD

**Issue by AgeOfMarcus** [colental/byob#15]
`root@kali:~/byob/byob# python server.py --host 127.0.0.1 --port 5000
DEBUG:core.util:missing package 'cv2' is required
Traceback (most recent call last):
  File "server.py", line 871, in <module>
    main()
  File "server.py", line 94, in main
    packages = [os.path.abspath(_) for _ in sys.path if os.path.isdir(_) if os.path.basename(_) == 'site-packages'][0]
IndexError: list index out of range
root@kali:~/byob/byob#`

I am running this on kali nethunter, aarch64.

**Comment by colental** [comment]
It looks like the 'site-packages' directory (which should contain any third-party packages/libraries you've installed, including the ones listed in requirements.txt) is not listed in sys.path 

Is there an alternate default location for user-installed third-party libraries that I should add?

**Comment by mshirley** [comment]
i'm not able to reproduce this with a fresh install.

```
user@userbox:~/src$ git clone https://github.com/colental/byob.git
Cloning into 'byob'...
cd byoremote: Counting objects: 735, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 735 (delta 17), reused 24 (delta 11), pack-reused 676
Receiving objects: 100% (735/735), 1.04 MiB | 0 bytes/s, done.
Resolving deltas: 100% (379/379), done.

Checking connectivity... done.

user@userbox:~/src$ cd byob
user@userbox:~/src/byob$ cd byob/
user@userbox:~/src/byob/byob$ python setup.py install
Password:
Installing mss==3.2.1...
[sudo] password for user:
Installing WMI==1.4.9...
Installing numpy==1.14.3...
Installing pyxhook==1.0.0...
Installing twilio==6.14.0...
Installing colorama==0.3.9...
Installing pyminifier==2.1...
Installing requests==2.18.4...
Installing PyInstaller==3.3.1...
Installing pycryptodome==3.6.1...
Installing opencv-python==3.4.1.15...
Installing pypiwin32==223...
user@userbox:~/src/byob/byob$ python server.py


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[?]  Hint: show usage information with the 'help' command

[user @ /home/user/src/byob/byob]>
```

**Comment by mshirley** [comment]
one recommendation is to install Anaconda or virtenv and use a virtual python environment rather than the base system environment.

**Comment by colental** [comment]
I agree with @mshirley - try a fresh-install and this issue should not occur. If for some reason the issue persists, please let me know
