### ISSUE TITLE
pypiwin32(pywin32) install error in linux. (Is pypiwin32 only for Windows?)

### ISSUE THREAD

**Issue by uCibar** [colental/byob#19]
When i try to install `requirements.txt` in linux, pip install all requirements except `pypiwin32`. When I try to install `pypiwin32` it gives an error like : 

> Could not find a version that satisfies the requirement pywin32>=223

But in Windows; pip successfuly install `pypiwin32`.

So, is pypiwin32(pywin32) package(s) only for Windows?

If it is; can we change `pypiwin32==223;` to `pypiwin32==223;sys_platform == 'Windows'` in `requirements.txt` for pypiwin32 package? In this way, pip don't try to install `pypiwin32` package for linux and we don't get error.

NOTE: I think there is a bug in` setup.py`. Because `setup.py` don't throw exception when install `requirement.txt` if there is an error. So, we can't see pypiwin32 error or other errors and we think; "setup.py successfully install packages." (Test it: add a random string named package to requirements.txt and run setup.py)

-Sorry for bad English.

**Comment by kondongx** [comment]
I got same error on Mac, and now I know why.

**Comment by mshirley** [comment]
seems perfectly reasonable from what i can tell.

the development of this code has been primarily in windows so bear with us as we work on making it multiplatform.

for the time being the only thing that seems to be using this library is the escalation process which is still under development. you should be able to safely ignore this error and still get a server and client running.

**Comment by colental** [comment]
Thanks for the feedback - the issue should now be fixed!

**Comment by pythonyhd** [comment]
这个问题还没有解决吗

**Comment by EzequielBurg** [comment]
How can I ignore this error running requirements.txt in a Dockerfile?

**Comment by maks1m** [comment]
> How can I ignore this error running requirements.txt in a Dockerfile, @mshirley ?

I had the same issue.
This workaround helped me ```pypiwin32==220; sys_platform == \'win32\'```

**Comment by kartik-555** [comment]
getting same issue cant find the solution

**Comment by SYK-08** [comment]
> > How can I ignore this error running requirements.txt in a Dockerfile, @mshirley ?
> 
> I had the same issue.
> This workaround helped me `pypiwin32==220; sys_platform == \'win32\'`

Can you please explain what you did?
I am also getting the same issues wonder if there is any similar module

**Comment by maks1m** [comment]
> > > How can I ignore this error running requirements.txt in a Dockerfile, @mshirley ?
> > 
> > 
> > I had the same issue.
> > This workaround helped me `pypiwin32==220; sys_platform == \'win32\'`
> 
> Can you please explain what you did?
> I am also getting the same issues wonder if there is any similar module

This module is just for windows platform and the workaround says to not install it on platforms other then windows.

**Comment by bhaveshchavda98** [comment]
I have same error in pypiwin32
