### ISSUE TITLE
After generating client, the server is not accessable/doesn't get started.

### ISSUE THREAD

**Issue by AgeOfMarcus** [colental/byob#4]
Command: `python client.py 127.0.0.1 8080`

It tells me that it is hosting the payload at 127.0.0.1:8081 but when I run the dropper it is unable to connect, and I do not see any services running a webserver on port 8081. Where does the payload get saved and do I need to manually start the server? If so, how?

PS I really like this program, I can learn a lot from it. Thank you!

**Comment by colental** [comment]
Hmm let me see if I can replicate the issue - I'll get back to you shortly!

**Comment by AgeOfMarcus** [comment]
Ok well I found where the payloads and stagers get saved, its in `modules/payloads` or `modules/stagers` but no server is getting started, it seems.

**Comment by xLinkOut** [comment]
Same here.
$ python client.py 127.0.0.1 6969
-> dropper created...

$ python server.py --host 127.0.0.1 --port 6969
-> Server started...

Server is accessible via browser, but when I try to start the payload it give me "Connection refused".
I've noticed that url in client generation process had a double slash "/" after port (like http://127.0.0.1:6969//payload...) but nothing changed.

**Comment by mshirley** [comment]
This is happening because the following line is commented out in the latest version (0.1.4)

```globals()['module_handler'] = subprocess.Popen('{} -m SimpleHTTPServer {}'.format(sys.executable, options.port + 1), 0, None, subprocess.PIPE, subprocess.PIPE, subprocess.PIPE, cwd=modules, shell=True)```

This is the process that starts a listener on 1338 or <port> + 1.  Once that service is started <host>:1338/payloads/ and <host>:1338/stagers/ should be accessible.

**Comment by mshirley** [comment]
i've created a pull request to fix this and a few other issues i've come across while getting things to work.

https://github.com/colental/byob/pull/13

**Comment by xLinkOut** [comment]
Nice, your version works well!

**Comment by colental** [comment]
Pull-request merged - thanks to @mshirley for the contribution and for fixing this issue!
